### ISSUE TITLE
我可以自定义头像api吗

### ISSUE THREAD

**Issue by pengwangzai** [NoonieBao/QAvatar#2]
我可以自己添加头像api源吗

**Comment by NoonieBao** [comment]
> 我可以自己添加头像api源吗

可以，但务必确保填入的url是可信的。并且只引入**1:1的png/jpg**，不要引入其它文件。

或者可以把图片复制到`/storage/emulated/0/Android/data/com.tencent.mobileqq/files/qavatar/`，程序也会自动更换。
